spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS  # Spring Batch 메타데이터 테이블 자동 생성
  datasource:
    url: jdbc:mysql://${MY_DB}:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    # password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      #      host: my-cache-server
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework:
      security: DEBUG
      web.socket: DEBUG
      messaging: DEBUG
    com.b110.jjeonchongmu: DEBUG

paging:
  default-page-size: 10
  default-page-number: 0

springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET_KEY}
#  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
#  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}
  access-token-validity: 3600
  refresh-token-validity: 2592000000

external:
  bank:
    api:
      url: ${EXTERNAL_BANK_URI}
      key: ${EXTERNAL_BANK_KEY}
      accountType: ${EXTERNAL_BANK_AT}
  user:
    api:
      url: ${EXTERNAL_USER_URI}

server:
  port: 8080