spring:
  datasource:
    url: jdbc:mysql://${MY_DB}:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    # password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: my-cache-server
#      host: localhost
      port: 6379

paging:
  default-page-size: 10
  default-page-number: 0

logging.level:
  org.hibernate.SQL: DEBUG
  org.springframework:
    security: DEBUG
    web.socket: DEBUG
    messaging: DEBUG
  com.b110.jjeonchongmu: DEBUG

springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: 86400000
  refresh-token-validity: 86400000


external:
  bank:
    api:
      url: ${EXTERNAL_BANK_URI}
      key: ${EXTERNAL_BANK_KEY}
      accountType: ${EXTERNAL_BANK_AT}
  user:
    api:
      url: ${EXTERNAL_USER_URI}

server:
  port: 8080