spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/jjeonchongmu?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

#  redis:
#    host: localhost
#    port: 6379
#    embedded:
#      enabled: true

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  access-token-validity: 1800000  # 30분
  refresh-token-validity: 604800000  # 7일

logging:
  level:
    com.b110.jjeonchongmu: DEBUG  # 프로젝트 로깅 레벨
    org.springframework.security: DEBUG  # Spring Security 로깅 레벨

external:
  bank:
    api:
      url: https://finopenapi.ssafy.io/ssafy/api/v1/edu/
      key: 4c56f9b9514141e3a39dd6783f4c536a