spring:
  datasource:
    url: jdbc:mysql://${MY_DB}:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    # password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      # host: localhost
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

paging:
  default-page-size: 10
  default-page-number: 0

logging.level:
  org.hibernate.SQL: DEBUG
  org.springframework:
    security: DEBUG
    web.socket: DEBUG
    messaging: DEBUG
  com.b110.jjeonchongmu: DEBUG

springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

  # access-token-validity: 3600000
  # refresh-token-validity: 2592000000

external:
  bank:
    api:
      url: ${EXTERNAL_BANK_API_URL}
      key: ${EXTERNAL_BANK_API_KEY}
      accountType: ${EXTERNAL_BANK_API_AT}
  user:
    api:
      url: ${EXTERNAL_USER_API_URL}

server:
  port: 8080